### ISSUE TITLE
this one is not working

### ISSUE THREAD

**Issue by kirrishima** [mcdominik/board_to_fen#2]
Traceback (most recent call last):
  File "...", line 1, in <module>
    from board_to_fen.predict import get_fen_from_image
  File "...\Lib\site-packages\board_to_fen\predict.py", line 3, in <module>
    from .KerasNeuralNetwork import KerasNeuralNetwork
  File "...\venv_bot\Lib\site-packages\board_to_fen\KerasNeuralNetwork.py", line 4, in <module>
    from keras import models, layers
ModuleNotFoundError: No module named 'keras'

**Comment by ArianDJ** [comment]
do "pip install keras" or "pip install keras --upgrade".
Easy solution, no need to open an issue for that next time.
